#!/bin/sh
apt-get update  # To get the latest package lists
apt-get install feh -y
apt-get install pavucontrol -y
apt-get install brightnessctl -y
apt-get install rofi -y
apt-get install polybar -y
apt-get install alacritty -y
apt-get install i3 -y
apt-get install steam -y
apt-get install gnome-control-center -y
#etc.
